"use strict";
exports.__esModule = true;
var circle_1 = require("./circle");
var rectangle_1 = require("./rectangle");
var acircle = new circle_1.Circle(2.5);
acircle.area();
acircle.display();
var arectangle = new rectangle_1.Rectangle(2, 3);
arectangle.area();
arectangle.display();
arectangle.setLength(5);
arectangle.setBreadth(10);
arectangle.area();
arectangle.display();
